apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-config"
  labels:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
