---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands-app
  template:
    metadata:
      labels:
        app: openhands-app
    spec:
      ################################################
      # Map host.docker.internal -> 127.0.0.1
      ################################################
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "host.docker.internal"

      containers:
        #################################################################
        # 1) DinD sidecar (Docker daemon)
        #################################################################
        - name: dind-daemon
          image: docker:20.10-dind
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: DOCKER_TLS_CERTDIR
              value: ""
          # Resource requests/limits for ~8 CPU / 16GB node
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
          volumeMounts:
            - name: dind-data
              mountPath: /var/lib/docker
            - name: dind-sock
              mountPath: /var/run/

        #################################################################
        # 2) Main container (OpenHands app)
        #################################################################
        - name: openhands-app
          image: docker.all-hands.dev/all-hands-ai/openhands:0.18
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: openhands-config
          env:
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: DOCKER_TLS_CERTDIR
              value: ""
          ports:
            - containerPort: 3000
              name: http
          # Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: openhands-state
              mountPath: /.openhands-state
            - name: dind-sock
              mountPath: /var/run/

      ###################################################################
      # Shared volumes for Docker socket & data + OpenHands state
      ###################################################################
      volumes:
        - name: dind-sock
          emptyDir: {}
        - name: dind-data
          persistentVolumeClaim:
            claimName: dind-data-pvc
        - name: openhands-state
          persistentVolumeClaim:
            claimName: openhands-state-pvc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhands-config
data:
  SANDBOX_RUNTIME_CONTAINER_IMAGE: "docker.all-hands.dev/all-hands-ai/runtime:0.18-nikolaik"
  LOG_ALL_EVENTS: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  # If no default StorageClass, specify one here:
  # storageClassName: "standard"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  # storageClassName: "standard"

---
apiVersion: v1
kind: Service
metadata:
  name: openhands-service
spec:
  type: LoadBalancer
  selector:
    app: openhands-app
  ports:
    - name: http
      port: 80
      targetPort: 3000