apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust as needed

  

  # If no default StorageClass, set storageClassName: "standard" or your own class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust as needed
    
