apiVersion: v1
kind: Service
metadata:
  name: openhands-service
spec:
  type: LoadBalancer
  # loadBalancerIP: 203.0.113.10  # some static ip later to be filled
  selector:
    app: openhands-app
  ports:
    - name: http
      port: 80
      targetPort: 3000