apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-dind-data-pvc"
  labels:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dindDataStorage }}
  # Uncomment and set if you have a specific StorageClass:
  # storageClassName: "standard"
