apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  selector:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
