replicaCount: 1

# Container images
images:
  dind:
    repository: docker
    tag: 20.10-dind
  openhands:
    repository: docker.all-hands.dev/all-hands-ai/openhands
    tag: "0.22"
    pullPolicy: Always

# Resources for the DinD sidecar
resources:
  dind:
    requests:
      cpu: "2"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "6Gi"

# Resources for the main container
openhandsResources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"

# ConfigMap data.
configMap:
  SANDBOX_RUNTIME_CONTAINER_IMAGE: "docker.all-hands.dev/all-hands-ai/runtime:0.22-nikolaik"
  LOG_ALL_EVENTS: "true"

# PVC storage sizes
pvc:
  dindDataStorage: "300Gi"
  openhandsStateStorage: "300Gi"

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
